// @flow

export const FETCH_CONTACTS_ERROR = "FETCH_CONTACTS_ERROR";
export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const SAVE_CONTACTS_SUCCESS = "SAVE_CONTACTS_SUCCESS";
